### PR TITLE
Set up Fink translation editor

### PR DESCRIPTION
**Pull request by NiklasBuchfink**
Hey @andydotxyz,

I'm from [inlang](https://inlang.com/), I saw your tweet this morning and wanted to know if I could get [Fink](https://inlang.com/m/tdozzpar/app-inlang-finkLocalizationEditor), the translation editor I'm working on, to run with your setup.

Let me know if this solution is suitable for `fyne` or what is missing.

**Preview:**
https://fink.inlang.com/github.com/NiklasBuchfink/fyne?branch=feature%2Ftranslations&project=%2Fproject.inlang

image

**Note:** The startup time is slow because we are cloning the repo into the browser. Soon, we will only fetch the translation files, which will be much faster.

### CODE REVIEW

**Comment by andydotxyz** [comment]
We are already sponsored by Weblate which works without config files in the repository.
Thanks for your interest, but I'm not sure why we would switch.

**Comment by NiklasBuchfink** [comment]
The sponsoring is a valid point and they also provide very good tooling, so I understand. I didn't know that as you tweeted about setting up Crowdin.

To explain the difference between Weblates' and inlangs' approaches. Weblate is based on syncing a Weblate repo with your repository and acts as an external service:
image

With inlang, all our apps, including the Fink localization editor, CLI, VS code extension, and the Parrot Figma plugin, are built around using your git repos as a source of truth and bringing version control to different departments.

image

For this reason, the CLI or the VS Code extension can coexist with Weblate without any problems, even if you do not use the localization editor.

Even if you don't use Inlang tools, it would be valuable to know whether this approach makes sense for you and whether you see the advantages over Weblate or Crowdin.

**Comment by andydotxyz** [comment]
> For this reason, the CLI or the VS Code extension can coexist with Weblate without any problems, even if you do not use the localization editor.

> Even if you don't use Inlang tools, it would be valuable to know whether this approach makes sense for you and whether you see the advantages over Weblate or Crowdin.

Sure it sounds interesting, but it would have to work without storing config files in our repo, as we don't commit the product specific files for optional tools.

**Comment by NiklasBuchfink** [comment]
Unfortunately, our tools only use the repo as a storage and a project directory with the settings file is required for all apps to work.

Thank you for your time and feedback 🙏

**Comment by andydotxyz** [comment]
If you decide to add some local storage for preferences / connection info etc let me know and I could test further.

**Pull request closed without merging**
